### ISSUE TITLE
sample code available?

### ISSUE THREAD

**Issue by jnovotny** [login-box/dropwizard-mybatis#18]
Hi,

I get errors when trying to use this module in my own dropwizard application:

! org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.vanare.perfengine.mappers.ActivityMapper.findAllActivity
But I have a package com.vanare.perfengine.mappers where I have both ActivityMapper and ActivityMapper.xml defined and findAllActivity is defined in both the interface and XML. What am I missing?

Here's how I configured:

private final MybatisBundle<PerformanceEngineConfiguration> mybatisBundle = new MybatisBundle<PerformanceEngineConfiguration>("com.vanare.perfengine") {
        @Override
        public DataSourceFactory getDataSourceFactory(PerformanceEngineConfiguration configuration) {
            return configuration.getDataSourceFactory();
        }
    };

Is there a simple demo application?

Thanks, Jason

**Comment by ojacobson** [comment]
There isn't, really. I wrote the module as part of work on login-box/login-box, but that's not so much a "demo" as "a half-baked mad dream." I should write one, one day.

I see you closed this - did you get your problem solved? If so, what was the root cause, and how could I make it less likely to come up for the next person? If not, I'm back in town and I can look into this.

**Comment by jnovotny** [comment]
Thanks a lot Owen, I appreciate the work you've done on this codebase! :-)

I figured my problem out-- I am using IntelliJ and I needed to put the 
mapping xml files in the resources/ directory but I had to also add the 
com/foo/ folders to mirror the java packages.

Cheers, Jason

**Comment by jnovotny** [comment]
Hi Owen,

I need to read from one DB and write to another requiring 2 session 
factories. Have you tried this before? I can't tell if I can use 2 
MybatisBundles or if I need to hack the MybatisBundle class to handle 
multiple session factories...

Thanks, Jason

**Comment by ojacobson** [comment]
Hi there! Glad you worked out the resource problem.

I would use two bundles (or, rather, one per DataSource[Factory]). That way, there's no ambiguity around transaction boundaries, or about which DB a given operation will be performed against.

Let me know how it works out!
